
all: print_start main print_end

print_start:
	@echo ""
	@echo "---- START BUILD ----"
	@echo ""

print_end:
	@echo ""
	@echo "---- END BUILD ----"
	@echo ""

main:
	@echo "pru_test1 building ..."
	@echo "PRU_CC $(PRU_CC)"
	@echo "PRU_LD $(PRU_LD)"
	@echo "PRU_CGT $(PRU_CGT)"
	 
clear:
	@echo "pru_test1 clearing ..."

.PHONY: all clear print_start print_end main

